/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

/**
 *
 * @author Dell
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnRecursosHumanos = new javax.swing.JButton();
        BtnReportesVenta = new javax.swing.JButton();
        BtnEntregas = new javax.swing.JButton();
        BtnPuntosVenta = new javax.swing.JButton();
        BtnInventario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image11.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 160, 70));

        BtnRecursosHumanos.setBackground(new java.awt.Color(255, 204, 0));
        BtnRecursosHumanos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnRecursosHumanos.setText("Recursos Humanos");
        BtnRecursosHumanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecursosHumanosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRecursosHumanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 150, 30));

        BtnReportesVenta.setBackground(new java.awt.Color(255, 204, 0));
        BtnReportesVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnReportesVenta.setText("Reportes de Venta");
        BtnReportesVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportesVentaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnReportesVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, 30));

        BtnEntregas.setBackground(new java.awt.Color(255, 204, 0));
        BtnEntregas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnEntregas.setText("Entregas");
        BtnEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntregasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 30));

        BtnPuntosVenta.setBackground(new java.awt.Color(255, 204, 0));
        BtnPuntosVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnPuntosVenta.setText("Puntos de Venta");
        BtnPuntosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPuntosVentaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPuntosVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, 30));

        BtnInventario.setBackground(new java.awt.Color(255, 204, 0));
        BtnInventario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnInventario.setText("Inventario");
        BtnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 150, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("La Preferida de Cajeme");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRecursosHumanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecursosHumanosActionPerformed
       // Crear una nueva instancia de FrmPuntosVenta
    FrmRecursosHumanos recursoshumanos = new FrmRecursosHumanos();
    
    // Hacer visible la ventana FrmPuntosVenta
   recursoshumanos.setVisible(true);
    
   
    this.dispose(); // Cierra el FrmMenu
    this.setVisible(false); // Solo oculta el FrmMenu
    }//GEN-LAST:event_BtnRecursosHumanosActionPerformed

    private void BtnReportesVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportesVentaActionPerformed
    // Crear una nueva instancia de FrmPuntosVenta
    FrmReporteVenta reporteVenta = new FrmReporteVenta();
    
    // Hacer visible la ventana FrmPuntosVenta
    reporteVenta.setVisible(true);
    
   
    this.dispose(); // Cierra el FrmMenu
    this.setVisible(false); // Solo oculta el FrmMenu
    }//GEN-LAST:event_BtnReportesVentaActionPerformed

    private void BtnEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntregasActionPerformed
    // Crear una nueva instancia de FrmPuntosVenta
    FrmEntregas registroPedido = new FrmEntregas();
    
    // Hacer visible la ventana FrmPuntosVenta
    registroPedido.setVisible(true);
    
   
    this.dispose(); // Cierra el FrmMenu
    this.setVisible(false); // Solo oculta el FrmMenu
    }//GEN-LAST:event_BtnEntregasActionPerformed

    private void BtnPuntosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPuntosVentaActionPerformed
      // Crear una nueva instancia de FrmPuntosVenta
    FrmPuntosVenta puntoVenta = new FrmPuntosVenta();
    
    // Hacer visible la ventana FrmPuntosVenta
    puntoVenta.setVisible(true);
    
   
    this.dispose(); // Cierra el FrmMenu
    this.setVisible(false); // Solo oculta el FrmMenu
    }//GEN-LAST:event_BtnPuntosVentaActionPerformed

    private void BtnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventarioActionPerformed
    // Crear una nueva instancia de FrmPuntosVenta
    FrmInventario inventario = new FrmInventario();
    
    // Hacer visible la ventana FrmPuntosVenta
    inventario.setVisible(true);
    
   
    this.dispose(); // Cierra el FrmMenu
    this.setVisible(false); // Solo oculta el FrmMenu
    }//GEN-LAST:event_BtnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntregas;
    private javax.swing.JButton BtnInventario;
    private javax.swing.JButton BtnPuntosVenta;
    private javax.swing.JButton BtnRecursosHumanos;
    private javax.swing.JButton BtnReportesVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
